### PR TITLE
Fix Create tests and DB models for error handlers

### PR DESCRIPTION
**Pull request by Hanhlin**
- Added tests for the create calls and method not allowed in `test_routes.py`
- Added date validation in `models.py`
- Code Coverage: 96%

### CODE REVIEW

**Comment by ruoyuGao** [comment]
It looks good to me, maybe you can create an issue for this PR, very happy to see our coverage increase a huge!!!

**Comment by KranthiGV** [comment]
LGTM

**Review by KranthiGV — APPROVED** [review]
LGTM

**Review by wonkwonlee — COMMENTED** [review]
Looks good!

**Pull request merged**
